### ISSUE TITLE
How to get transactions from bitcoin chain? zmq or rpc?

### ISSUE THREAD

**Issue by worldmars** [commerceblock/federation#11]

**Comment by nkostoulas** [comment]
What are you trying to do?

**Comment by worldmars** [comment]
yes, but No instructions for running

**Comment by nkostoulas** [comment]
Federation works with any bitcoin-based rpc. You only need to provide rpc connectivity details.

**Comment by worldmars** [comment]
--rpconnect  --rpcport: rpc --rpcuser: rpc username --rpcpassword: rpc password？

**Comment by nkostoulas** [comment]
Yep

**Comment by worldmars** [comment]
There are questions about the interpretation of the parameters in the readme？

**Comment by nkostoulas** [comment]
What questions?

**Comment by worldmars** [comment]
--rpconnect is  Ocean node or bitcoin node?

**Comment by nkostoulas** [comment]
It's for an Ocean or Elements node, as it uses rpc calls specific to these that don't exist in bitcoin.

**Comment by worldmars** [comment]
Can you explain how the code of federation works?

**Comment by nkostoulas** [comment]
It's an application build to do federated block signing. For a given federation, of say X members, each node takes turns producing a block which it shares with the other nodes via zmq/Kafka, collects these signatures, combines them and produces the block. Each federation member runs an Ocean node and an instance of this application that connects to the node.

**Comment by worldmars** [comment]
Does it not handle transactions that are locked to a federated address?

**Comment by nkostoulas** [comment]
How do you mean? There's currently no peg-in peg-out functionality in the federation.
